# Generated by Django 5.2.5 on 2025-08-10 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('court', 'start_time')},
        ),
    ]
