# Generated by Django 5.2.5 on 2025-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='court',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
