# Generated by Django 5.2.5 on 2025-08-15 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_court_is_available_court_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.court')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('court', 'date', 'start_time')},
            },
        ),
    ]
