# Generated by Django 5.2.5 on 2025-08-16 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courtslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtslot',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slots', to=settings.AUTH_USER_MODEL),
        ),
    ]
