# Generated by Django 5.2.5 on 2025-08-23 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_member_user_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
