# Generated by Django 5.2.5 on 2025-08-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_member_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '⬇ Export Members',
                'verbose_name_plural': '⬇ Export Members',
                'managed': False,
            },
        ),
    ]
