# Generated by Django 5.2.5 on 2025-08-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_exportmembers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportMembers',
        ),
        migrations.CreateModel(
            name='ExportMembers',
            fields=[
            ],
            options={
                'verbose_name': 'Export Members',
                'verbose_name_plural': 'Export Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.member',),
        ),
    ]
