# Generated by Django 5.2.5 on 2025-09-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtslot',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
